spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 本地数据库
    username: root
    password: twb
    url: jdbc:mysql://localhost/friend_match
  # 设置session会话失效时间 一天
  session:
    timeout: 86400

server:
  port: 8080
  servlet:
    # url  -> http://localhost:8080/api/
    context-path: /api
#    session:
#      cookie:
#        same-site: None
#        secure: true

  # mapUnderscoreToCamelCase 是否开启自动驼峰命名规则（camel case）映射，
  #即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 开启查询日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置  官方文档：https://baomidou.com/pages/6b03c5/#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  enable: true
  openapi:
    title: 伙伴匹配系统
    description: 接口文档
    email: 1493440094@qq.com
    concat: 云漪
    url: https://github.com/cloud-ripple
    version: v4.0
    license: Apache 2.0
    license-url: https://github.com/cloud-ripple
    terms-of-service-url: https://github.com/cloud-ripple
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.ripple.friend.controller